<?php

namespace App\Http\Controllers\Voyager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CodeController extends VoyagerBaseController
{
    public function store(\Illuminate\Http\Request $request)
    {
        $request->validate($this->rules());
        return parent::store($request); // TODO: Change the autogenerated stub
    }
    public function update(\Illuminate\Http\Request $request, $id)
    {
        $request->validate($this->rules());
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
    public function rules(){
        return [
            'value_discount' => [function($field, $data, $fail){
                if(!request()->get('value_discount') && !\request()->get('percentage_discount')) $fail('Musisz wybrać albo zniżkę procentową, albo zniżkę liczbową');
            }],
            'percentage_discount' => [function($field, $data, $fail){
            if(!request()->get('value_discount') && !\request()->get('percentage_discount')) $fail('Musisz wybrać albo zniżkę procentową, albo zniżkę liczbową');
            }]
        ];
    }
}
