<?php

namespace App\Http\Controllers\Voyager;

use App\Shop\Order;
use http\Env\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerBaseController;

class OrderController extends BaseVoyagerBaseController
{
    public function index(\Illuminate\Http\Request $request)
    {
        $parent = parent::index($request); // TODO: Change the autogenerated stub
        $dataTypeContent = Order::where('id', '>', 0);
        if($request->status && $request->status != ''){
            $dataTypeContent = $dataTypeContent->where('status', $request->status);
        }
        if($request->paid && $request->paid == 'on'){
            $dataTypeContent = $dataTypeContent->where('paid', 1);
        }
        $dataTypeContent = $dataTypeContent->get();
        return $parent->with(['dataTypeContent' => $dataTypeContent]);
    }
}
