<?php

namespace App\Http\Controllers\Voyager;

use App\Helpers\Helper;
use App\Http\Controllers\Voyager\VoyagerBaseController;
use App\Product;
use Illuminate\Http\Request;
use PHPUnit\TextUI\Help;

class ProductController extends VoyagerBaseController
{
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
    public function update(Request $request, $id)
    {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
    public function settings($id){
        $product = Product::find($id);
        return view('vendor.voyager.products.settings', compact('product'));
    }
}
