<?php

namespace App\Http\Controllers\Voyager;

use Carbon\Carbon;
use Carbon\CarbonInterval;
use Carbon\CarbonPeriod;
use PragmaRX\Tracker\Vendor\Laravel\Facade as Tracker;
use TCG\Voyager\Http\Controllers\VoyagerController as BaseVoyagerController;

class VoyagerController extends BaseVoyagerController
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
}
